spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baijiajie?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    properties: 
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
cbs: 
  imagesPath: file:/E:/PartTimeJob/weixin/baijiajie/src/main/resources/pics/